services:
  api:                  # vorher: 'backend'
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ticket-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./config/form.schema.json:/config/form.schema.json:ro
    restart: unless-stopped
    networks: [appnet]

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: ticket-frontend
    ports:
      - "80:80"
    depends_on: [api]
    restart: unless-stopped
    networks: [appnet]

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks: [appnet]

networks:
  appnet:
    driver: bridge
